// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2PO6qj1H-90xqhecjwXQ38wiEJXD0A7Y',
    appId: '1:713898000759:web:52b45da2872c7e620d2172',
    messagingSenderId: '713898000759',
    projectId: 'myfinancesbr',
    authDomain: 'myfinancesbr.firebaseapp.com',
    storageBucket: 'myfinancesbr.appspot.com',
    measurementId: 'G-JHL06NNFCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtwNmYyLhCnhJh1dybY63CDrE8VWDE1o',
    appId: '1:713898000759:android:d79f714b262eb2fd0d2172',
    messagingSenderId: '713898000759',
    projectId: 'myfinancesbr',
    storageBucket: 'myfinancesbr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY0414TUAPWY3Zlmj5NoEalbHpL82IC9c',
    appId: '1:713898000759:ios:f0d1508261da95340d2172',
    messagingSenderId: '713898000759',
    projectId: 'myfinancesbr',
    storageBucket: 'myfinancesbr.appspot.com',
    iosClientId: '713898000759-91dr66o7anovi4e7r20aul95lqe0nfdu.apps.googleusercontent.com',
    iosBundleId: 'com.eduardoazvd.myfinances',
  );
}
