// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2PO6qj1H-90xqhecjwXQ38wiEJXD0A7Y',
    appId: '1:713898000759:web:abfc559661949ae60d2172',
    messagingSenderId: '713898000759',
    projectId: 'myfinancesbr',
    authDomain: 'myfinancesbr.firebaseapp.com',
    storageBucket: 'myfinancesbr.appspot.com',
    measurementId: 'G-XP6B3HBTT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtwNmYyLhCnhJh1dybY63CDrE8VWDE1o',
    appId: '1:713898000759:android:d58242f8f5ee51f40d2172',
    messagingSenderId: '713898000759',
    projectId: 'myfinancesbr',
    storageBucket: 'myfinancesbr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY0414TUAPWY3Zlmj5NoEalbHpL82IC9c',
    appId: '1:713898000759:ios:901bbe817f9749560d2172',
    messagingSenderId: '713898000759',
    projectId: 'myfinancesbr',
    storageBucket: 'myfinancesbr.appspot.com',
    iosClientId: '713898000759-jn5pjb4i5oj8i8st01n08mbdndbl7rk5.apps.googleusercontent.com',
    iosBundleId: 'com.eduardoazevedo.myfinances',
  );
}
